Vagrant.configure("2") do |config|

    config.vm.box_download_insecure = true

    for i in 1..3 do
        config.vm.define "node-#{i}" do |node|
            node.vm.provider "docker" do |d|
              d.image = "redis"
            end
        end
    end
  end