
configuracoes = {
  "work1"   =>  { "images" => "centos/7", "memory" => "1256", "cpu" => "1", "ip" => "101" },
  "work2"   =>  { "images" => "centos/7", "memory" => "1256", "cpu" => "1", "ip" => "101" },
  "work3"   =>  { "images" => "centos/7", "memory" => "1256", "cpu" => "1", "ip" => "101" },
}

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  configuracoes.each do |nome,capacity|
    config.vm.define "#{nome}" do |maquina|
      maquina.vm.box      = "#{capacity["images"]}"
      maquina.vm.network "private_network", ip: "10.5.25.#{capacity["ip"]}"
      maquina.vm.hostname = "#{nome}.pensandoemlinuxcom"
      maquina.vm.provider "virtualbox" do |customizando|
        customizando.cpus   = "#{capacity["cpu"]}"
        customizando.memory = "#{capacity["memory"]}"
        customizando.name   = "#{nome}"
        # Pode ser declarado desta forma
        # customizando.name   = nome
        customizando.customize ["modifyvm", :id, "--groups", "/Elasticsearch"]
        
        # Tambem pode estar declarando array desta forma
        # customizando.memory = capacity["memory"]
        # customizando.cpus   = capacity["cpu"]
      end  
    end
  end
end
